### ISSUE TITLE
feature request - parameterize the 'tmp' directory

### ISSUE THREAD

**Issue by mengano-net** [zapling/plantuml.nvim#1]
Thanks for the work. 

I would like to suggest a feature.
To parameterize the 'tmp' directory and configure it via calling the setup() function. 

- I'm in macos but have restrictions via enterprise policy even on the /tmp directory, so got this on first run:

```
Error executing Lua callback: Vim:E482: Can't open file /tmp/plantuml_nvim/index.html for writing: no such file or directory
stack traceback:
        [C]: in function 'writefile'
        ...im/site/pack/packer/start/plantuml.nvim/lua/plantuml.lua:44: in function 'setup_tmp_dir'
        ...im/site/pack/packer/start/plantuml.nvim/lua/plantuml.lua:60: in function 'entrypoint'
        ...im/site/pack/packer/start/plantuml.nvim/lua/plantuml.lua:74: in function <...im/site/pack/packer/start/plantuml.nvim/lua/plantuml.lua:74>
```

- I wonder if you could build a parameter here:
```
local function setup_tmp_dir()
    vim.fn.jobstart('[[ ! -d /tmp/plantuml_nvim ]] && mkdir /tmp/plantuml_nvim')
    vim.fn.writefile(vim.split(index_html, '\n'), '/tmp/plantuml_nvim/index.html')
end
```

... which then can get configured via calling the setup() function?

by the way, here is my plugin configuration smippet:
```
    use {
        'zapling/plantuml.nvim',
        requires = { 'nvim-lua/plenary.nvim' },
        config = function()
            require('plantuml').setup()
        end
    }
```

... and my version on macos
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by zapling** [comment]
Sounds like a great idea! I have created a PR for this, it works for me, do you mind testing it so we can confirm it solves your issue before merging #2 . With that change you should be able to do 
```
require("plantuml").setup({tmp_dir = '/tmp/other-dir'})
```
